//! Synthetic fixture generator (CLAUDE.md: "Use synthetic fixtures only,
//! generated by xtask/"). Produces a diverse, fully synthetic test corpus:
//! one sample per supported extension, plus a duplicate of each stored in a
//! GUID-named subfolder under a randomized filename. txt/html/htm
//! duplicates get a trailing "lorem epsum" line (a genuine near-duplicate);
//! everything else is byte-identical (an exact duplicate).
//!
//! Usage: `cargo run -p xtask -- [out_dir] [samples_per_format]`
//! Defaults: out_dir = "data", samples_per_format = 3.

use std::fs;
use std::io::{Cursor, Write};
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let out_dir = args
        .first()
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("data"));
    let samples_per_format: usize = args.get(1).and_then(|s| s.parse().ok()).unwrap_or(3);

    match generate_fixtures(&out_dir, samples_per_format) {
        Ok(count) => {
            println!(
                "xtask: generated {count} format(s) x {samples_per_format} sample(s) (+1 duplicate each) under {}",
                out_dir.display()
            );
            println!(
                "xtask: note - png/jpg/jpeg/gif/bmp/tiff/msg fixtures carry correct magic-number headers but \
                 are not fully valid/renderable files. The tool only exact-hashes them today (no image \
                 decoding or MSG parsing), so this is sufficient for current test coverage."
            );
        }
        Err(err) => {
            eprintln!("xtask: failed to generate fixtures: {err}");
            std::process::exit(1);
        }
    }
}

struct Format {
    ext: &'static str,
    make: fn(usize) -> Vec<u8>,
    /// txt/html/htm duplicates get a mutated (near-duplicate) copy; every
    /// other format's duplicate is byte-identical (an exact duplicate).
    mutatable_text: bool,
}

const FORMATS: &[Format] = &[
    Format {
        ext: "pdf",
        make: make_pdf,
        mutatable_text: false,
    },
    Format {
        ext: "png",
        make: make_png,
        mutatable_text: false,
    },
    Format {
        ext: "jpg",
        make: make_jpg,
        mutatable_text: false,
    },
    Format {
        ext: "jpeg",
        make: make_jpg,
        mutatable_text: false,
    },
    Format {
        ext: "gif",
        make: make_gif,
        mutatable_text: false,
    },
    Format {
        ext: "bmp",
        make: make_bmp,
        mutatable_text: false,
    },
    Format {
        ext: "tiff",
        make: make_tiff,
        mutatable_text: false,
    },
    Format {
        ext: "eml",
        make: make_eml,
        mutatable_text: false,
    },
    Format {
        ext: "msg",
        make: make_msg,
        mutatable_text: false,
    },
    Format {
        ext: "docx",
        make: make_docx,
        mutatable_text: false,
    },
    Format {
        ext: "xlsx",
        make: make_xlsx,
        mutatable_text: false,
    },
    Format {
        ext: "pptx",
        make: make_pptx,
        mutatable_text: false,
    },
    Format {
        ext: "csv",
        make: make_csv,
        mutatable_text: false,
    },
    Format {
        ext: "tsv",
        make: make_tsv,
        mutatable_text: false,
    },
    Format {
        ext: "txt",
        make: make_txt,
        mutatable_text: true,
    },
    Format {
        ext: "md",
        make: make_md,
        mutatable_text: false,
    },
    Format {
        ext: "html",
        make: make_html,
        mutatable_text: true,
    },
    Format {
        ext: "htm",
        make: make_html,
        mutatable_text: true,
    },
    Format {
        ext: "xml",
        make: make_xml,
        mutatable_text: false,
    },
    Format {
        ext: "json",
        make: make_json,
        mutatable_text: false,
    },
    Format {
        ext: "yaml",
        make: make_yaml,
        mutatable_text: false,
    },
    Format {
        ext: "yml",
        make: make_yaml,
        mutatable_text: false,
    },
    Format {
        ext: "rtf",
        make: make_rtf,
        mutatable_text: false,
    },
];

fn generate_fixtures(out_dir: &Path, samples_per_format: usize) -> std::io::Result<usize> {
    if out_dir.exists() {
        fs::remove_dir_all(out_dir)?;
    }
    fs::create_dir_all(out_dir)?;

    let mut rng = Rng::new(seed_from_time());

    for format in FORMATS {
        let format_dir = out_dir.join(format.ext);
        fs::create_dir_all(&format_dir)?;

        for n in 1..=samples_per_format {
            let original_bytes = (format.make)(n);
            let original_name = format!("sample_{n:02}.{}", format.ext);
            fs::write(format_dir.join(&original_name), &original_bytes)?;

            let duplicate_bytes = if format.mutatable_text {
                let mut mutated = original_bytes.clone();
                mutated.extend_from_slice(b"\nlorem epsum\n");
                mutated
            } else {
                original_bytes.clone()
            };

            let dup_dir = format_dir.join(rng.guid());
            fs::create_dir_all(&dup_dir)?;
            let dup_name = format!("sample_{n:02}{}.{}", rng.alphanumeric_char(), format.ext);
            fs::write(dup_dir.join(dup_name), &duplicate_bytes)?;
        }
    }

    Ok(FORMATS.len())
}

// ---- Format generators ---------------------------------------------------
//
// Content is filler text with no meaning beyond exercising duplicate and
// similarity detection. Image/eml-adjacent binary formats (png, jpg, jpeg,
// gif, bmp, tiff, msg) carry correct magic-number headers but are not fully
// valid, renderable/parseable files - the engine only exact-hashes these
// formats today, so byte-identity is all that is required.

fn make_txt(n: usize) -> Vec<u8> {
    format!(
        "Synthetic test document {n}\n\n\
         This is filler content generated for drive-migrator similarity testing. \
         It has no meaning beyond exercising duplicate detection.\n"
    )
    .into_bytes()
}

fn make_md(n: usize) -> Vec<u8> {
    format!(
        "# Synthetic Document {n}\n\n\
         This is **filler** content generated for drive-migrator testing.\n\n\
         - point one\n- point two\n"
    )
    .into_bytes()
}

fn make_html(n: usize) -> Vec<u8> {
    format!(
        "<html><body><h1>Synthetic Document {n}</h1>\
         <p>Filler content for drive-migrator testing.</p></body></html>"
    )
    .into_bytes()
}

fn make_csv(n: usize) -> Vec<u8> {
    format!("id,name,value\n{n},alpha,100\n{},beta,200\n", n + 1).into_bytes()
}

fn make_tsv(n: usize) -> Vec<u8> {
    format!("id\tname\tvalue\n{n}\talpha\t100\n{}\tbeta\t200\n", n + 1).into_bytes()
}

fn make_json(n: usize) -> Vec<u8> {
    format!("{{\"id\": {n}, \"name\": \"doc-{n}\", \"tags\": [\"synthetic\", \"test\"]}}")
        .into_bytes()
}

fn make_xml(n: usize) -> Vec<u8> {
    format!("<root><id>{n}</id><note>synthetic test content</note></root>").into_bytes()
}

fn make_yaml(n: usize) -> Vec<u8> {
    format!("id: {n}\nname: doc-{n}\ntags:\n  - synthetic\n  - test\n").into_bytes()
}

fn make_rtf(n: usize) -> Vec<u8> {
    format!("{{\\rtf1\\ansi Synthetic document {n} filler content for testing today\\par}}")
        .into_bytes()
}

fn make_eml(n: usize) -> Vec<u8> {
    format!(
        "From: sender{n}@example.test\r\nTo: recipient{n}@example.test\r\n\
         Subject: Synthetic message {n}\r\nDate: Mon, 1 Jan 2024 00:00:00 +0000\r\n\r\n\
         This is a synthetic email body for testing.\r\n"
    )
    .into_bytes()
}

fn make_msg(n: usize) -> Vec<u8> {
    // Not a real OLE compound file; the engine does not parse .msg
    // internals yet, so distinguishable filler bytes are sufficient.
    format!("SYNTHETIC-MSG-PLACEHOLDER document {n} filler content").into_bytes()
}

fn make_pdf(n: usize) -> Vec<u8> {
    format!(
        "%PDF-1.4\n\
         1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n\
         2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n\
         3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 200 200]>>endobj\n\
         trailer<</Root 1 0 R>>\n\
         %%Synthetic document {n}\n%%EOF\n"
    )
    .into_bytes()
}

fn make_png(n: usize) -> Vec<u8> {
    let mut bytes = vec![0x89, b'P', b'N', b'G', 0x0D, 0x0A, 0x1A, 0x0A];
    bytes.extend_from_slice(format!("SYNTHETIC-PNG-PLACEHOLDER-{n}").as_bytes());
    bytes
}

fn make_jpg(n: usize) -> Vec<u8> {
    let mut bytes = vec![0xFF, 0xD8, 0xFF, 0xE0];
    bytes.extend_from_slice(format!("SYNTHETIC-JPEG-PLACEHOLDER-{n}").as_bytes());
    bytes.extend_from_slice(&[0xFF, 0xD9]);
    bytes
}

fn make_gif(n: usize) -> Vec<u8> {
    let mut bytes = b"GIF89a".to_vec();
    bytes.extend_from_slice(format!("SYNTHETIC-GIF-PLACEHOLDER-{n}").as_bytes());
    bytes
}

fn make_bmp(n: usize) -> Vec<u8> {
    let mut bytes = b"BM".to_vec();
    bytes.extend_from_slice(format!("SYNTHETIC-BMP-PLACEHOLDER-{n}").as_bytes());
    bytes
}

fn make_tiff(n: usize) -> Vec<u8> {
    let mut bytes = vec![b'I', b'I', 42, 0];
    bytes.extend_from_slice(format!("SYNTHETIC-TIFF-PLACEHOLDER-{n}").as_bytes());
    bytes
}

fn make_docx(n: usize) -> Vec<u8> {
    let document_xml = format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\
         <w:document xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\">\
         <w:body><w:p><w:r><w:t>Synthetic document {n} filler content for testing</w:t></w:r></w:p>\
         </w:body></w:document>"
    );
    zip_bytes(&[("word/document.xml", document_xml.as_bytes())])
}

fn make_pptx(n: usize) -> Vec<u8> {
    let slide_xml = format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\
         <p:sld xmlns:a=\"http://schemas.openxmlformats.org/drawingml/2006/main\" \
         xmlns:p=\"http://schemas.openxmlformats.org/presentationml/2006/main\">\
         <p:cSld><p:spTree><p:sp><p:txBody><a:p><a:r><a:t>Synthetic slide {n} filler content</a:t></a:r></a:p>\
         </p:txBody></p:sp></p:spTree></p:cSld></p:sld>"
    );
    zip_bytes(&[("ppt/slides/slide1.xml", slide_xml.as_bytes())])
}

fn make_xlsx(n: usize) -> Vec<u8> {
    let content_types = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\
        <Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\">\
        <Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/>\
        <Default Extension=\"xml\" ContentType=\"application/xml\"/>\
        <Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/>\
        <Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/>\
        </Types>";

    let root_rels = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\
        <Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">\
        <Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/>\
        </Relationships>";

    let workbook_xml = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\
        <workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" \
        xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\">\
        <sheets><sheet name=\"Sheet1\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>";

    let workbook_rels = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\
        <Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">\
        <Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/>\
        </Relationships>";

    let sheet_xml = format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\
         <worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\">\
         <sheetData><row r=\"1\"><c r=\"A1\" t=\"inlineStr\"><is><t>doc-{n}</t></is></c>\
         <c r=\"B1\"><v>{n}</v></c></row></sheetData></worksheet>"
    );

    zip_bytes(&[
        ("[Content_Types].xml", content_types.as_bytes()),
        ("_rels/.rels", root_rels.as_bytes()),
        ("xl/workbook.xml", workbook_xml.as_bytes()),
        ("xl/_rels/workbook.xml.rels", workbook_rels.as_bytes()),
        ("xl/worksheets/sheet1.xml", sheet_xml.as_bytes()),
    ])
}

fn zip_bytes(entries: &[(&str, &[u8])]) -> Vec<u8> {
    let mut buf = Vec::new();
    {
        let cursor = Cursor::new(&mut buf);
        let mut zip = zip::ZipWriter::new(cursor);
        let options = zip::write::SimpleFileOptions::default();
        for (name, content) in entries {
            zip.start_file(*name, options).expect("zip start_file");
            zip.write_all(content).expect("zip write_all");
        }
        zip.finish().expect("zip finish");
    }
    buf
}

// ---- Minimal deterministic-enough PRNG for folder/file naming ------------
//
// Not cryptographic; only needs to produce plausible-looking, very-unlikely
// -to-collide GUIDs and filename suffixes for a few hundred fixture files.

struct Rng {
    state: u64,
}

impl Rng {
    fn new(seed: u64) -> Self {
        Self { state: seed }
    }

    fn next_u64(&mut self) -> u64 {
        self.state = self.state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    fn hex_string(&mut self, len: usize) -> String {
        const HEX: &[u8] = b"0123456789abcdef";
        (0..len)
            .map(|_| {
                let idx = (self.next_u64() % 16) as usize;
                HEX[idx] as char
            })
            .collect()
    }

    fn guid(&mut self) -> String {
        format!(
            "{}-{}-{}-{}-{}",
            self.hex_string(8),
            self.hex_string(4),
            self.hex_string(4),
            self.hex_string(4),
            self.hex_string(12)
        )
    }

    fn alphanumeric_char(&mut self) -> char {
        const ALPHABET: &[u8] = b"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        let idx = (self.next_u64() % ALPHABET.len() as u64) as usize;
        ALPHABET[idx] as char
    }
}

fn seed_from_time() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0x5EED)
}
