//! Synthetic fixture generator (CLAUDE.md: "Use synthetic fixtures only,
//! generated by xtask/"). Produces a diverse, fully synthetic test corpus
//! nested under a handful of "project" folders (mimicking a real migration
//! source tree), with:
//!
//! - Multi-way exact duplicates: each original gets 2 byte-identical copies
//!   in separate GUID-named subfolders (a 3-member duplicate group).
//! - Genuine multi-generation near-duplicates for txt/html/htm: each
//!   original produces a 2-generation version chain (gen1 adds a line to
//!   the original, gen2 adds another line to gen1), nested progressively
//!   deeper to mimic real version drift.
//! - Decoy files with genuinely unrelated content (not just a different
//!   embedded number) for every format `similar` supports, so there are
//!   real true-negatives to sift through, not just near-identical samples.
//!
//! The output is deterministic (fixed RNG seed) so committing it doesn't
//! churn on every regeneration unless the generator itself changes.
//!
//! Usage: `cargo run -p xtask -- [out_dir] [samples_per_format]`
//! Defaults: out_dir = "data", samples_per_format = 4.

use std::fs;
use std::io::{Cursor, Write};
use std::path::{Path, PathBuf};

const FIXED_SEED: u64 = 0xD21A_5EED_C0FF_EE42;
const PROJECTS: &[&str] = &["project-alpha", "project-beta", "project-gamma"];
const DECOYS_PER_FORMAT: usize = 2;

// Combinatorial decoy sentences: each decoy gets a distinct subject/verb/
// object combination (keyed by a seed unique across all format+index
// combinations), so decoys are genuinely unrelated to each other, not just
// to the real samples. A single shared sentence would make every decoy
// cross-match every other decoy as a near-duplicate.
const DECOY_SUBJECTS: &[&str] = &[
    "the committee",
    "migratory birds",
    "volcanic activity",
    "the research team",
    "quarterly revenue",
    "the shipping container",
    "wildlife biologists",
    "the software update",
];
const DECOY_VERBS: &[&str] = &[
    "reviewed",
    "traveled across",
    "reshaped",
    "documented",
    "exceeded",
    "arrived at",
    "tracked",
    "improved",
];
const DECOY_OBJECTS: &[&str] = &[
    "the annual budget proposal",
    "the northern coastline",
    "several remote field stations",
    "expectations for the fiscal year",
    "the regional distribution center",
    "population trends in the reserve",
    "startup latency across all regions",
];

fn decoy_sentence(seed: usize) -> String {
    let subject = DECOY_SUBJECTS[seed % DECOY_SUBJECTS.len()];
    let verb = DECOY_VERBS[(seed / DECOY_SUBJECTS.len()) % DECOY_VERBS.len()];
    let object =
        DECOY_OBJECTS[(seed / (DECOY_SUBJECTS.len() * DECOY_VERBS.len())) % DECOY_OBJECTS.len()];
    format!("{subject} {verb} {object}")
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let out_dir = args
        .first()
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("data"));
    let samples_per_format: usize = args.get(1).and_then(|s| s.parse().ok()).unwrap_or(4);

    match generate_fixtures(&out_dir, samples_per_format) {
        Ok(count) => {
            println!(
                "xtask: generated {count} format(s) x {samples_per_format} sample(s) under {}",
                out_dir.display()
            );
            println!(
                "xtask: note - png/jpg/jpeg/gif/bmp/tiff/msg fixtures carry correct magic-number headers but \
                 are not fully valid/renderable files. The tool only exact-hashes them today (no image \
                 decoding or MSG parsing), so this is sufficient for current test coverage."
            );
        }
        Err(err) => {
            eprintln!("xtask: failed to generate fixtures: {err}");
            std::process::exit(1);
        }
    }
}

struct Format {
    ext: &'static str,
    make: fn(usize) -> Vec<u8>,
    /// `Some` for every format `similar` supports, producing content with
    /// genuinely different wording (not just a different number) so there
    /// are real true-negatives in the corpus.
    decoy: Option<fn(usize) -> Vec<u8>>,
    /// txt/html/htm duplicates become a 2-generation near-duplicate chain;
    /// every other format's duplicates are byte-identical (exact
    /// duplicates).
    mutatable_text: bool,
}

const FORMATS: &[Format] = &[
    Format {
        ext: "pdf",
        make: make_pdf,
        decoy: None,
        mutatable_text: false,
    },
    Format {
        ext: "png",
        make: make_png,
        decoy: None,
        mutatable_text: false,
    },
    Format {
        ext: "jpg",
        make: make_jpg,
        decoy: None,
        mutatable_text: false,
    },
    Format {
        ext: "jpeg",
        make: make_jpg,
        decoy: None,
        mutatable_text: false,
    },
    Format {
        ext: "gif",
        make: make_gif,
        decoy: None,
        mutatable_text: false,
    },
    Format {
        ext: "bmp",
        make: make_bmp,
        decoy: None,
        mutatable_text: false,
    },
    Format {
        ext: "tiff",
        make: make_tiff,
        decoy: None,
        mutatable_text: false,
    },
    Format {
        ext: "eml",
        make: make_eml,
        decoy: None,
        mutatable_text: false,
    },
    Format {
        ext: "msg",
        make: make_msg,
        decoy: None,
        mutatable_text: false,
    },
    Format {
        ext: "docx",
        make: make_docx,
        decoy: Some(make_docx_decoy),
        mutatable_text: false,
    },
    Format {
        ext: "xlsx",
        make: make_xlsx,
        decoy: Some(make_xlsx_decoy),
        mutatable_text: false,
    },
    Format {
        ext: "pptx",
        make: make_pptx,
        decoy: Some(make_pptx_decoy),
        mutatable_text: false,
    },
    Format {
        ext: "csv",
        make: make_csv,
        decoy: Some(make_csv_decoy),
        mutatable_text: false,
    },
    Format {
        ext: "tsv",
        make: make_tsv,
        decoy: Some(make_tsv_decoy),
        mutatable_text: false,
    },
    Format {
        ext: "txt",
        make: make_txt,
        decoy: Some(make_txt_decoy),
        mutatable_text: true,
    },
    Format {
        ext: "md",
        make: make_md,
        decoy: Some(make_md_decoy),
        mutatable_text: false,
    },
    Format {
        ext: "html",
        make: make_html,
        decoy: Some(make_html_decoy),
        mutatable_text: true,
    },
    Format {
        ext: "htm",
        make: make_html,
        decoy: Some(make_html_decoy),
        mutatable_text: true,
    },
    Format {
        ext: "xml",
        make: make_xml,
        decoy: Some(make_xml_decoy),
        mutatable_text: false,
    },
    Format {
        ext: "json",
        make: make_json,
        decoy: Some(make_json_decoy),
        mutatable_text: false,
    },
    Format {
        ext: "yaml",
        make: make_yaml,
        decoy: Some(make_yaml_decoy),
        mutatable_text: false,
    },
    Format {
        ext: "yml",
        make: make_yaml,
        decoy: Some(make_yaml_decoy),
        mutatable_text: false,
    },
    Format {
        ext: "rtf",
        make: make_rtf,
        decoy: Some(make_rtf_decoy),
        mutatable_text: false,
    },
];

fn generate_fixtures(out_dir: &Path, samples_per_format: usize) -> std::io::Result<usize> {
    if out_dir.exists() {
        fs::remove_dir_all(out_dir)?;
    }
    fs::create_dir_all(out_dir)?;

    let mut rng = Rng::new(FIXED_SEED);

    for (format_index, format) in FORMATS.iter().enumerate() {
        for n in 1..=samples_per_format {
            let project = PROJECTS[(format_index + n) % PROJECTS.len()];
            let format_dir = out_dir.join(project).join(format.ext);
            fs::create_dir_all(&format_dir)?;

            let original_bytes = (format.make)(n);
            let original_name = format!("sample_{n:02}.{}", format.ext);
            fs::write(format_dir.join(&original_name), &original_bytes)?;

            if format.mutatable_text {
                // A genuine 2-generation version chain, nested progressively
                // deeper: gen1 adds a line to the original, gen2 adds
                // another line to gen1.
                let mut gen1 = original_bytes.clone();
                gen1.extend_from_slice(b"\nlorem epsum\n");
                let gen1_dir = format_dir.join(rng.guid());
                fs::create_dir_all(&gen1_dir)?;
                let gen1_name = format!("sample_{n:02}{}.{}", rng.alphanumeric_char(), format.ext);
                fs::write(gen1_dir.join(&gen1_name), &gen1)?;

                let mut gen2 = gen1.clone();
                gen2.extend_from_slice(b"\nsecond revision note\n");
                let gen2_dir = gen1_dir.join(rng.guid());
                fs::create_dir_all(&gen2_dir)?;
                let gen2_name = format!("sample_{n:02}{}.{}", rng.alphanumeric_char(), format.ext);
                fs::write(gen2_dir.join(gen2_name), &gen2)?;
            } else {
                // Two byte-identical copies in separate GUID subfolders: a
                // 3-member exact-duplicate group (original + 2 copies).
                for _ in 0..2 {
                    let dup_dir = format_dir.join(rng.guid());
                    fs::create_dir_all(&dup_dir)?;
                    let dup_name =
                        format!("sample_{n:02}{}.{}", rng.alphanumeric_char(), format.ext);
                    fs::write(dup_dir.join(dup_name), &original_bytes)?;
                }
            }
        }

        if let Some(decoy) = format.decoy {
            for d in 1..=DECOYS_PER_FORMAT {
                // Globally unique across every format+index combination, so
                // two different formats' decoys never land on the same
                // sentence (see decoy_sentence's doc comment).
                let seed = format_index * 100 + d;
                let project = PROJECTS[(format_index + d + 1) % PROJECTS.len()];
                let format_dir = out_dir.join(project).join(format.ext);
                fs::create_dir_all(&format_dir)?;
                let bytes = decoy(seed);
                let name = format!("decoy_{d:02}.{}", format.ext);
                fs::write(format_dir.join(name), &bytes)?;
            }
        }
    }

    Ok(FORMATS.len())
}

// ---- Format generators ---------------------------------------------------
//
// Content is filler text with no meaning beyond exercising duplicate and
// similarity detection. Image/eml-adjacent binary formats (png, jpg, jpeg,
// gif, bmp, tiff, msg) carry correct magic-number headers but are not fully
// valid, renderable/parseable files - the engine only exact-hashes these
// formats today, so byte-identity is all that is required.

fn make_txt(n: usize) -> Vec<u8> {
    format!(
        "Synthetic test document {n}\n\n\
         This is filler content generated for drive-migrator similarity testing. \
         It has no meaning beyond exercising duplicate detection.\n"
    )
    .into_bytes()
}

fn make_txt_decoy(n: usize) -> Vec<u8> {
    let sentence = decoy_sentence(n);
    format!("Unrelated note {n}\n\n{sentence}\n").into_bytes()
}

fn make_md(n: usize) -> Vec<u8> {
    format!(
        "# Synthetic Document {n}\n\n\
         This is **filler** content generated for drive-migrator testing.\n\n\
         - point one\n- point two\n"
    )
    .into_bytes()
}

fn make_md_decoy(n: usize) -> Vec<u8> {
    let sentence = decoy_sentence(n);
    format!("# Unrelated Note {n}\n\n{sentence}\n").into_bytes()
}

fn make_html(n: usize) -> Vec<u8> {
    format!(
        "<html><body><h1>Synthetic Document {n}</h1>\
         <p>Filler content for drive-migrator testing.</p></body></html>"
    )
    .into_bytes()
}

fn make_html_decoy(n: usize) -> Vec<u8> {
    let sentence = decoy_sentence(n);
    format!("<html><body><h1>Unrelated {n}</h1><p>{sentence}</p></body></html>").into_bytes()
}

fn make_csv(n: usize) -> Vec<u8> {
    format!("id,name,value\n{n},alpha,100\n{},beta,200\n", n + 1).into_bytes()
}

fn make_csv_decoy(n: usize) -> Vec<u8> {
    let sentence = decoy_sentence(n);
    format!("id,topic,note\n{n},biology,\"{sentence}\"\n").into_bytes()
}

fn make_tsv(n: usize) -> Vec<u8> {
    format!("id\tname\tvalue\n{n}\talpha\t100\n{}\tbeta\t200\n", n + 1).into_bytes()
}

fn make_tsv_decoy(n: usize) -> Vec<u8> {
    let sentence = decoy_sentence(n);
    format!("id\ttopic\tnote\n{n}\tbiology\t{sentence}\n").into_bytes()
}

fn make_json(n: usize) -> Vec<u8> {
    format!("{{\"id\": {n}, \"name\": \"doc-{n}\", \"tags\": [\"synthetic\", \"test\"]}}")
        .into_bytes()
}

fn make_json_decoy(n: usize) -> Vec<u8> {
    let sentence = decoy_sentence(n);
    format!("{{\"id\": {n}, \"topic\": \"biology\", \"note\": \"{sentence}\"}}").into_bytes()
}

fn make_xml(n: usize) -> Vec<u8> {
    format!("<root><id>{n}</id><note>synthetic test content</note></root>").into_bytes()
}

fn make_xml_decoy(n: usize) -> Vec<u8> {
    let sentence = decoy_sentence(n);
    format!("<root><id>{n}</id><note>{sentence}</note></root>").into_bytes()
}

fn make_yaml(n: usize) -> Vec<u8> {
    format!("id: {n}\nname: doc-{n}\ntags:\n  - synthetic\n  - test\n").into_bytes()
}

fn make_yaml_decoy(n: usize) -> Vec<u8> {
    let sentence = decoy_sentence(n);
    format!("id: {n}\ntopic: biology\nnote: \"{sentence}\"\n").into_bytes()
}

fn make_rtf(n: usize) -> Vec<u8> {
    format!("{{\\rtf1\\ansi Synthetic document {n} filler content for testing today\\par}}")
        .into_bytes()
}

fn make_rtf_decoy(n: usize) -> Vec<u8> {
    let sentence = decoy_sentence(n);
    format!("{{\\rtf1\\ansi Unrelated {n} {sentence}\\par}}").into_bytes()
}

fn make_eml(n: usize) -> Vec<u8> {
    format!(
        "From: sender{n}@example.test\r\nTo: recipient{n}@example.test\r\n\
         Subject: Synthetic message {n}\r\nDate: Mon, 1 Jan 2024 00:00:00 +0000\r\n\r\n\
         This is a synthetic email body for testing.\r\n"
    )
    .into_bytes()
}

fn make_msg(n: usize) -> Vec<u8> {
    // Not a real OLE compound file; the engine does not parse .msg
    // internals yet, so distinguishable filler bytes are sufficient.
    format!("SYNTHETIC-MSG-PLACEHOLDER document {n} filler content").into_bytes()
}

fn make_pdf(n: usize) -> Vec<u8> {
    format!(
        "%PDF-1.4\n\
         1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n\
         2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n\
         3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 200 200]>>endobj\n\
         trailer<</Root 1 0 R>>\n\
         %%Synthetic document {n}\n%%EOF\n"
    )
    .into_bytes()
}

fn make_png(n: usize) -> Vec<u8> {
    let mut bytes = vec![0x89, b'P', b'N', b'G', 0x0D, 0x0A, 0x1A, 0x0A];
    bytes.extend_from_slice(format!("SYNTHETIC-PNG-PLACEHOLDER-{n}").as_bytes());
    bytes
}

fn make_jpg(n: usize) -> Vec<u8> {
    let mut bytes = vec![0xFF, 0xD8, 0xFF, 0xE0];
    bytes.extend_from_slice(format!("SYNTHETIC-JPEG-PLACEHOLDER-{n}").as_bytes());
    bytes.extend_from_slice(&[0xFF, 0xD9]);
    bytes
}

fn make_gif(n: usize) -> Vec<u8> {
    let mut bytes = b"GIF89a".to_vec();
    bytes.extend_from_slice(format!("SYNTHETIC-GIF-PLACEHOLDER-{n}").as_bytes());
    bytes
}

fn make_bmp(n: usize) -> Vec<u8> {
    let mut bytes = b"BM".to_vec();
    bytes.extend_from_slice(format!("SYNTHETIC-BMP-PLACEHOLDER-{n}").as_bytes());
    bytes
}

fn make_tiff(n: usize) -> Vec<u8> {
    let mut bytes = vec![b'I', b'I', 42, 0];
    bytes.extend_from_slice(format!("SYNTHETIC-TIFF-PLACEHOLDER-{n}").as_bytes());
    bytes
}

fn make_docx(n: usize) -> Vec<u8> {
    docx_bytes(&format!(
        "Synthetic document {n} filler content for testing"
    ))
}

fn make_docx_decoy(n: usize) -> Vec<u8> {
    let sentence = decoy_sentence(n);
    docx_bytes(&format!("Unrelated {n} {sentence}"))
}

fn docx_bytes(text: &str) -> Vec<u8> {
    let document_xml = format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\
         <w:document xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\">\
         <w:body><w:p><w:r><w:t>{text}</w:t></w:r></w:p></w:body></w:document>"
    );
    zip_bytes(&[("word/document.xml", document_xml.as_bytes())])
}

fn make_pptx(n: usize) -> Vec<u8> {
    pptx_bytes(&format!("Synthetic slide {n} filler content"))
}

fn make_pptx_decoy(n: usize) -> Vec<u8> {
    let sentence = decoy_sentence(n);
    pptx_bytes(&format!("Unrelated {n} {sentence}"))
}

fn pptx_bytes(text: &str) -> Vec<u8> {
    let slide_xml = format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\
         <p:sld xmlns:a=\"http://schemas.openxmlformats.org/drawingml/2006/main\" \
         xmlns:p=\"http://schemas.openxmlformats.org/presentationml/2006/main\">\
         <p:cSld><p:spTree><p:sp><p:txBody><a:p><a:r><a:t>{text}</a:t></a:r></a:p>\
         </p:txBody></p:sp></p:spTree></p:cSld></p:sld>"
    );
    zip_bytes(&[("ppt/slides/slide1.xml", slide_xml.as_bytes())])
}

fn make_xlsx(n: usize) -> Vec<u8> {
    xlsx_bytes(&format!("doc-{n}"), &n.to_string())
}

fn make_xlsx_decoy(n: usize) -> Vec<u8> {
    xlsx_bytes(&format!("unrelated-{n}"), &(n + 9000).to_string())
}

fn xlsx_bytes(label: &str, value: &str) -> Vec<u8> {
    let content_types = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\
        <Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\">\
        <Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/>\
        <Default Extension=\"xml\" ContentType=\"application/xml\"/>\
        <Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/>\
        <Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/>\
        </Types>";

    let root_rels = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\
        <Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">\
        <Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/>\
        </Relationships>";

    let workbook_xml = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\
        <workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" \
        xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\">\
        <sheets><sheet name=\"Sheet1\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>";

    let workbook_rels = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\
        <Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">\
        <Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/>\
        </Relationships>";

    let sheet_xml = format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\
         <worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\">\
         <sheetData><row r=\"1\"><c r=\"A1\" t=\"inlineStr\"><is><t>{label}</t></is></c>\
         <c r=\"B1\"><v>{value}</v></c></row></sheetData></worksheet>"
    );

    zip_bytes(&[
        ("[Content_Types].xml", content_types.as_bytes()),
        ("_rels/.rels", root_rels.as_bytes()),
        ("xl/workbook.xml", workbook_xml.as_bytes()),
        ("xl/_rels/workbook.xml.rels", workbook_rels.as_bytes()),
        ("xl/worksheets/sheet1.xml", sheet_xml.as_bytes()),
    ])
}

fn zip_bytes(entries: &[(&str, &[u8])]) -> Vec<u8> {
    let mut buf = Vec::new();
    {
        let cursor = Cursor::new(&mut buf);
        let mut zip = zip::ZipWriter::new(cursor);
        let options = zip::write::SimpleFileOptions::default();
        for (name, content) in entries {
            zip.start_file(*name, options).expect("zip start_file");
            zip.write_all(content).expect("zip write_all");
        }
        zip.finish().expect("zip finish");
    }
    buf
}

// ---- Minimal deterministic PRNG for folder/file naming --------------------
//
// Not cryptographic; only needs to produce plausible-looking, very-unlikely
// -to-collide GUIDs and filename suffixes, deterministically from a fixed
// seed so the committed corpus doesn't churn between regenerations.

struct Rng {
    state: u64,
}

impl Rng {
    fn new(seed: u64) -> Self {
        Self { state: seed }
    }

    fn next_u64(&mut self) -> u64 {
        self.state = self.state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    fn hex_string(&mut self, len: usize) -> String {
        const HEX: &[u8] = b"0123456789abcdef";
        (0..len)
            .map(|_| {
                let idx = (self.next_u64() % 16) as usize;
                HEX[idx] as char
            })
            .collect()
    }

    fn guid(&mut self) -> String {
        format!(
            "{}-{}-{}-{}-{}",
            self.hex_string(8),
            self.hex_string(4),
            self.hex_string(4),
            self.hex_string(4),
            self.hex_string(12)
        )
    }

    fn alphanumeric_char(&mut self) -> char {
        const ALPHABET: &[u8] = b"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        let idx = (self.next_u64() % ALPHABET.len() as u64) as usize;
        ALPHABET[idx] as char
    }
}
