//! Exercises the engine against the committed synthetic corpus under
//! `data/` (generated by `cargo run -p xtask`, fully synthetic per
//! CLAUDE.md's hard rule). Runs automatically via `cargo test --all` on
//! every OS in CI - no separate workflow step needed.

mod common;

use std::path::PathBuf;

use common::TempTree;

fn data_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../data")
}

#[test]
fn analyze_finds_duplicates_in_the_committed_corpus() {
    let dir = data_dir();
    if !dir.exists() {
        eprintln!("skipping: {} not present", dir.display());
        return;
    }

    let mut cache = engine::FingerprintCache::default();
    let report = engine::analyze(&[dir], &mut cache).expect("analyze should succeed");

    assert!(
        report.files_scanned > 200,
        "expected a sizeable corpus, got {}",
        report.files_scanned
    );
    assert!(
        report.duplicate_groups.len() > 50,
        "expected many exact-duplicate groups, got {}",
        report.duplicate_groups.len()
    );
}

#[test]
fn similar_finds_near_duplicates_with_no_decoy_cross_matches() {
    let dir = data_dir();
    if !dir.exists() {
        return;
    }

    let report = engine::find_similar(&[dir], &engine::SimilarityConfig::default())
        .expect("similar should succeed");

    assert!(
        !report.pairs.is_empty(),
        "expected at least some near-duplicate pairs"
    );

    // Decoys are built with genuinely distinct content specifically so they
    // never match anything, including each other - if one shows up here,
    // the fixture generator's decoy sentences collided again.
    for pair in &report.pairs {
        let a = pair.a.to_string_lossy();
        let b = pair.b.to_string_lossy();
        assert!(
            !a.contains("decoy") && !b.contains("decoy"),
            "decoy file unexpectedly matched: {a} <-> {b}"
        );
    }
}

#[test]
fn full_migration_round_trip_against_the_committed_corpus() {
    let dir = data_dir();
    if !dir.exists() {
        return;
    }

    let tree = TempTree::new();
    let dest = tree.path().join("dest");

    let mut cache = engine::FingerprintCache::default();
    let rules = engine::PreflightRules::default();
    let plan = engine::plan(&dir, &dest, &mut cache, &rules).expect("plan should succeed");
    let summary = engine::run(&plan, &engine::RunOptions::default()).expect("run should succeed");
    assert_eq!(
        summary.failed, 0,
        "no file should fail to copy from a clean synthetic corpus"
    );

    let manifest =
        engine::write_manifest(&dest, Some(&dir)).expect("write_manifest should succeed");
    assert!(manifest.file_count > 0);

    let verify_report = engine::verify(&dest).expect("verify should succeed");
    assert!(verify_report.integrity.trusted);
    assert!(verify_report.changed.is_empty());
    assert!(verify_report.deleted.is_empty());
}
